# Generated by Django 3.1.2 on 2020-12-08 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.CharField(blank=True, max_length=50)),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=14, verbose_name='Бaланас')),
            ],
        ),
        migrations.CreateModel(
            name='UserGun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='weapon/', verbose_name='Фотография оружия')),
                ('name', models.CharField(max_length=20, verbose_name='Название оружия')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Цена оружия')),
                ('rarity', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('name', models.CharField(max_length=20, verbose_name='Название кейса')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Цена кейса')),
                ('image', models.ImageField(upload_to='case/', verbose_name='Фотография кейса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
