# Generated by Django 3.1.2 on 2020-12-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Уровень редкости')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='Тип оружия')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weapon/', verbose_name='Фотография оружия')),
                ('name', models.CharField(max_length=20, verbose_name='Название оружия')),
                ('rar', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weapon/', verbose_name='Фотография оружия')),
                ('name', models.CharField(max_length=20, verbose_name='Название оружия')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Цена оружия')),
                ('level_of_rarity', models.SmallIntegerField(blank=True, choices=[(None, 'Выберите уровень редкости оружия'), (1, 'Гавно'), (2, 'Получше'), (3, 'Норм такой'), (4, 'Пездато')], verbose_name='Уровень редкости')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tools.rarity')),
                ('type_of_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tools.typeofweapon')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружия',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название кейса')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Цена кейса')),
                ('image', models.ImageField(upload_to='case/', verbose_name='Фотография кейса')),
                ('weapon', models.ManyToManyField(to='app_tools.Weapon', verbose_name='Оружие')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
    ]
