# Generated by Django 3.1.2 on 2020-12-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='level_of_rarity',
        ),
    ]
