# Generated by Django 3.1.2 on 2020-12-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tools', '0002_remove_weapon_level_of_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tools.rarity', verbose_name='Уровень редкости'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type_of_weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tools.typeofweapon', verbose_name='Тип оружия'),
        ),
    ]
