# Generated by Django 3.1.2 on 2020-12-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tools', '0004_auto_20201209_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name': 'Уровень редкости оружия', 'verbose_name_plural': 'Уровени редкости оружий'},
        ),
        migrations.AlterModelOptions(
            name='typeofweapon',
            options={'verbose_name': 'Вид оружия', 'verbose_name_plural': 'Виды оружий'},
        ),
    ]
